### ISSUE TITLE
I can't see git-diff highlighting with this syntax

### ISSUE THREAD

**Issue by bakana808** [DanielPintilei/cake-atom-syntax#2]
For some reason, I can't see the [`git-diff`](https://github.com/atom/git-diff) highlighting when using this syntax. I've did some testing and I can see them on every single theme I have installed -- except this one. Changing the UI didn't help either. It's worth noting, though, that I _can_ see the icons if `Show Icons In Editor Gutter` is enabled.

Sorry, I can't provide much technical information, but what I can tell you is that this is happening on Atom 1.8.0, on a Windows 10 64-bit system. 

I love the colors, so here's hoping to a fast solve, or at the very least a workaround in the meantime.

**Comment by DanielPintilei** [comment]
I can see the highlighting on new lines but not on modified lines with atom-material-ui and atom dark or light. Works fine with one-dark-ui. I'll look into it.

**Comment by DanielPintilei** [comment]
For some reason `@syntax-color-modified: @tag;` bugs, while `@syntax-color-modified: #fe728b;` works. I'll fix this later today.
